### ISSUE TITLE
CUAHSI Hydroinformatics Innovation Fellowship

### ISSUE THREAD

**Issue by samzipper** [Gromopo/GroMoPo#26]
**Links**
- [Proposal google doc](https://docs.google.com/document/d/16_K6p3lbFKt-BknCPBrF9h2aXktr1wdAv3cAUKapf6A/edit?usp=sharing) 
- [Fellowship info/instructions](https://www.cuahsi.org/data-models/hydroinformatics-innovation-fellowship/)

**Steps**
- [x] budget to KUCR
- [x] CV
- [ ] draft narrative to team
- [ ] draft narrative to KUCR
- [ ] compile into single PDF
- [ ] submit

**Comment by samzipper** [comment]
- [ ] budget
- [ ] CV
- [ ] draft narrative

**Comment by rreinecke** [comment]
I think this done. Closing it to clean up the issues a bit.
