### ISSUE TITLE
Use the hydroshare API to save data from the form

### ISSUE THREAD

**Issue by rreinecke** [Gromopo/GroMoPo#30]
It is possibly not that easy to query data from hydroshare so we might need to keep a very simple database in the app to cache resources and approvements.

https://www.hydroshare.org/hsapi/
https://pypi.org/project/hsclient/

**Comment by rreinecke** [comment]
Parts of this are now implemented. Metadata can be pushed to hydroshare from the form.

Current todos and obstacles:

- [ ] File upload of shapefiles still bugy
- [ ] Build up proper testing framework for field checks -> this should be a separate issue
- [ ] Upload to hydroshare requires login data -> we should check if we are running on a streamlit server and pull the jonfig with password etc. from a place. We don't want the password and username in the git repo
- [ ] implement data query and download (including caching for displaying the data)

**Comment by samzipper** [comment]
I think @kristyj004 has completed this
