### ISSUE TITLE
Move streamlit main to streamlit.io gromopo

### ISSUE THREAD

**Issue by rreinecke** [Gromopo/GroMoPo#34]
@kbefus Could you move the main app to the new gromopo accout as well?
Is the login information documented somewhere? Just in case somebody else needs to access the streamlit.io account during development?

**Comment by kbefus** [comment]
According to the settings on streamlit, anyone with push rights on here can manage the app - use the link in the develop branch to go to the app, then there should be a little manage button on the bottom right if you are signed in to github.

**Comment by rreinecke** [comment]
For me there is only hosted by streamlit button.

**Comment by kbefus** [comment]
Did you link your github account to streamlit? Gromopo doesn't show up as one of "my" apps when I'm logged in there - the only way I can access the app is with the develop link.

**Comment by rreinecke** [comment]
Ok that was the important piece of information that was missing. No I did not.
Thanks!
