### ISSUE TITLE
Image in about page is still the wrong one

### ISSUE THREAD

**Issue by rreinecke** [Gromopo/GroMoPo#74]
We still use the possible copyright infringement image on the About page instead of the new logo.

**Comment by yuritaba** [comment]
Hi, I would love to contribute to your code, could you please elaborate more on this issue?
When I access the "about page" I can only see a diagram besides the text. Is that the copyright infringement image you're referring to?

**Comment by rreinecke** [comment]
I've removed the old image in this commit: https://github.com/Gromopo/GroMoPo/commit/88aabe946570dd8e3e3dd5e38e7bf9b459a4130d

The new monster image is already available here https://github.com/Gromopo/GroMoPo/tree/main/images

**Comment by rreinecke** [comment]
The old image was based on the cooky-monster and thus unusable. Kevin made a new monster that we are already using in presentations but not yet on the website. Would be great if this could be fixed!

**Comment by yuritaba** [comment]
Working on it. Thank you!
